name: Capsule Seal Protocol

on:
  push:
    paths:
      - 'Museum/**'
      - 'capsules/**'
      - '.github/workflows/Seal.yml'

jobs:
  seal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload Museum artifacts
        uses: actions/upload-artifact@v4
        with:
          name: museum-artifacts
          path: Museum/

      - name: Upload Capsule artifacts
        uses: actions/upload-artifact@v4
        with:
          name: capsule-artifacts
          path: capsules/
